services:
  - type: web
    name: ecommerce-api
    env: python
    plan: free
    # Note: Render may automatically use Python 3.13
    # Our requirements.txt is now compatible with Python 3.13
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
    plan: free
