services:
  - type: web
    name: ecommerce-api
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabaseSecret: DATABASE_URL
      - key: FLASK_APP
        value: wsgi.py
    postDeployCommand: flask db upgrade

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
    plan: free